image: node:latest

stages:
- test
- publish

before_script:
- git submodule update --init --recursive
- source .ci-env
- npm install -g @nofrills/tasks@7.1.7
- cli-tasks ci:install

cache:
  paths:
  - node_modules

hotfix:
  stage: publish
  only:
  - /feature\/.*/
  - /hotfix\/.*/
  script:
  - cli-tasks ci:publish:canary

prerelease:
  stage: publish
  only:
  - develop
  script:
  - cli-tasks ci:publish:prerelease

release:
  stage: publish
  only:
  - master
  script:
  - cli-tasks ci:publish:release
  - cli-tasks ci:deploy
