image: docker:dind

stages:
  - test
  - release
  - publish
  - deploy

services:
  - docker:dind

before_script:
  - apk --update --no-cache add bash chromium curl git grep gzip jq nodejs npm openssh-client tar
  - echo -n $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
  - source .ci-env.sh
  - bash .citools/setup-git ${BUILD_REPO_BRANCH} ${BUILD_REPO_GIT} ${BUILD_REPO_EMAIL}
  - bash .citools/setup-ssh ${BUILD_REPO_DOMAIN} ${BUILD_REPO_SSHKEY_PATH} ${BUILD_REPO_DOMAIN_SSH}
  - curl -sL https://github.com/digitalocean/doctl/releases/download/v1.46.0/doctl-1.46.0-linux-amd64.tar.gz | tar -xzv && mv doctl /bin
  - curl -sLO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && chmod +x kubectl && mv kubectl /bin
  - doctl kubernetes cluster kubeconfig save nativecode

test:
  stage: test
  artifacts:
    untracked: true
  script:
    - npm ci || exit 1
    - npm run build || exit 1
    - export CHROME_BIN="/usr/bin/chromium-browser"
    - npm run test:headless || exit 1
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

feature:
  stage: release
  artifacts:
    untracked: true
  needs:
    - test
  only:
    - /^feature\/.*$/
  script:
    - npm -s run lerna -- changed > .changed || exit 1
    - npm -s run lerna -- publish --conventional-commits --conventional-prerelease --no-changelog --canary --preid $CI_COMMIT_REF_NAME --yes || exit 1

prerelease:
  stage: release
  artifacts:
    untracked: true
  only:
    - develop
  script:
    - npm -s run lerna -- changed > .changed || exit 1
    - npm -s run lerna -- version --conventional-commits --conventional-prerelease --no-changelog --yes || exit 1

release:
  stage: release
  artifacts:
    untracked: true
  only:
    - master
  script:
    - npm -s run lerna -- changed > .changed || exit 1
    - npm -s run lerna -- version --conventional-commits --conventional-graduate --yes || exit 1

docker:
  stage: publish
  artifacts:
    untracked: true
  only:
    - tags
  script:
    - npm ci || exit 1
    - npm run docker:publish || exit 1
  variables:
    DOCKER_HOST: tcp://localhost:2375
    GIT_SUBMODULE_STRATEGY: recursive
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
