image: docker:dind

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

stages:
  - test
  - release
  - publish
  - deploy

services:
  - docker:dind

before_script:
  - apk --update --no-cache add bash chromium curl git grep gzip jq nodejs npm openssh-client tar
  - echo -n $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
  - source .ci-env.sh
  - bash .citools/setup-git ${BUILD_REPO_BRANCH} ${BUILD_REPO_GIT} ${BUILD_REPO_EMAIL}
  - bash .citools/setup-ssh ${BUILD_REPO_DOMAIN} ${BUILD_REPO_SSHKEY_PATH} ${BUILD_REPO_DOMAIN_SSH}
  - curl -sL https://github.com/digitalocean/doctl/releases/download/v1.46.0/doctl-1.46.0-linux-amd64.tar.gz | tar -xzv && mv doctl /bin
  - curl -sLO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && chmod +x kubectl && mv kubectl /bin
  - doctl kubernetes cluster kubeconfig save nativecode
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc

test:
  stage: test
  artifacts:
    untracked: true
  script:
    - npm ci --cache .npm --prefer-offline || exit 1
    - npm run build || exit 1
    - export CHROME_BIN="/usr/bin/chromium-browser"
    - npm run lint || exit 1
    - npm run test:headless || exit 1
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

feature:
  stage: release
  needs:
    - test
  only:
    - /^feature\/.*$/
  script:
    - bash scripts/publish-packages.sh canary $CI_COMMIT_REF_NAME
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

prerelease:
  stage: release
  needs:
    - test
  only:
    - develop
  script:
    - bash scripts/publish-packages.sh prerelease
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

release:
  stage: release
  needs:
    - test
  only:
    - master
  script:
    - bash scripts/publish-packages.sh release
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

docker:
  stage: publish
  needs:
    - test
  only:
    - tags
  script:
    - bash scripts/publish-docker.sh latest || exit 1
  variables:
    DOCKER_HOST: tcp://localhost:2375
    GIT_SUBMODULE_STRATEGY: recursive
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

deploy:
  stage: deploy
  needs:
    - test
  only:
    - tags
  script:
    - kubectl apply -f deploy.yaml || exit 1
  variables:
    DOCKER_HOST: tcp://localhost:2375
    GIT_SUBMODULE_STRATEGY: recursive
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
