version: '3.3'

services:
  app-ui:
    image: nativecode/kabuce-appui:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - node_modules:/usr/app/node_modules

volumes:
  node_modules:
