name: build
on:
  push:
    branches:
      - .*
    tags-ignore:
      - .*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: npm-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-build-${{ env.cache-name }}-${{ matrix.node-version }}-
            npm-build-${{ env.cache-name }}-
            npm-build-
            npm-

      - name: Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test:headless

      - name: kabuce-api
        uses: actions/upload-artifact@v2
        with:
          name: kabuce-api-${{ matrix.node-version }}
          path: |
            packages/kabuce-api/dist
            packages/kabuce-api/package-lock.json
            packages/kabuce-api/package.json
            packages/kabuce-api/swagger.json

      - name: kabuce-app
        uses: actions/upload-artifact@v2
        with:
          name: kabuce-app-${{ matrix.node-version }}
          path: |
            packages/kabuce-app/dist
            packages/kabuce-app/package-lock.json
            packages/kabuce-app/package.json
