name: build

on:
  push:
    branches:
      - develop
      - master
      - "features/**"
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: npm-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-build-${{ env.cache-name }}-${{ matrix.node-version }}-
            npm-build-${{ env.cache-name }}-
            npm-build-
            npm-
      - name: dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: test
        run: npm run test:headless
      - name: kabuce-api
        uses: actions/upload-artifact@v2
        with:
          name: kabuce-api
          path: packages/kabuce-api/dist
      - name: kabuce-app
        uses: actions/upload-artifact@v2
        with:
          name: kabuce-app
          path: packages/kabuce-app/dist
