name: publish
on:
  push:
    tags:
      - "v[0-9].*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore Artifacts API
        uses: actions/download-artifact@v2
        with:
          name: kabuce-api-12.x

      - name: Restore Artifacts App
        uses: actions/download-artifact@v2
        with:
          name: kabuce-app-12.x

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1

      - name: Docker Hub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Publish API
        uses: docker/build-push-action@v2
        with:
          context: packages/kabuce-api
          file: packages/kabuce-api/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: nativecode/kabuce-api:latest

      - name: Publish App
        uses: docker/build-push-action@v2
        with:
          context: packages/kabuce-app
          file: packages/kabuce-app/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: nativecode/kabuce-app:latest
