name: release
on:
  push:
    tags:
      - "v[0-9].*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: restore-artifacts
        uses: actions/download-artifact@v2
        with:
          name: kabuce-api-12.x
