name: release
on:
  push:
    tags:
      - "v[0-9].*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore API Artifacts
        uses: actions/download-artifact@v2
        with:
          name: kabuce-api-12.x

      - name: Restore App Artifacts
        uses: actions/download-artifact@v2
        with:
          name: kabuce-app-12.x

      - name: test
        run: npm test
